export interface CallCenter{
  id:number,
  name: string,
  uniqueId: string,
  mobile: string,
  gender: string,
  Address: string,
  shift: string,
  email: string,
  status: string,
  createdAt: string,
  updatedAt: string,
  userId: number,
  totalBookings: number,
  emergencyBookings: number,
}